# Generated by Django 3.0.10 on 2020-09-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Castle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Castle',
                'verbose_name_plural': 'Castles',
            },
        ),
    ]
