# Generated by Django 3.0.10 on 2020-09-27 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='castle',
            name='title',
        ),
        migrations.AddField(
            model_name='castle',
            name='bijschrift',
            field=models.CharField(default=None, max_length=255, verbose_name='bijschrift'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='castle',
            name='cchin',
            field=models.IntegerField(default=None, verbose_name='cchin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='castle',
            name='datering_year',
            field=models.PositiveIntegerField(default=2020, help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2020)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='castle',
            name='foto_groot',
            field=models.CharField(default='foo', max_length=255, verbose_name='foto_groot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='castle',
            name='foto_thumb',
            field=models.CharField(default='foo', max_length=255, verbose_name='foto_thumb'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='castle',
            name='geometry_coords_x',
            field=models.IntegerField(default=12, verbose_name='geometry coordinates x-axis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='castle',
            name='geometry_coords_y',
            field=models.IntegerField(default=23, verbose_name='geometry coordinates y-axis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='castle',
            name='geometry_name',
            field=models.CharField(default='foo', max_length=25, verbose_name='geometry_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='castle',
            name='geometry_type',
            field=models.CharField(default='dd', max_length=25, verbose_name='Geometry type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='castle',
            name='gid',
            field=models.IntegerField(default=2, verbose_name='gid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='castle',
            name='iid',
            field=models.CharField(default='we', max_length=25, verbose_name='id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='castle',
            name='info_link',
            field=models.CharField(default='ssss', max_length=255, verbose_name='info link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='castle',
            name='itype',
            field=models.CharField(default='qwq', max_length=25, verbose_name='type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='castle',
            name='legenda',
            field=models.CharField(default='ss', max_length=255, verbose_name='legenda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='castle',
            name='naam',
            field=models.CharField(default='qwqw', max_length=255, unique=True, verbose_name='naam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='castle',
            name='plaats',
            field=models.CharField(default='sdss', max_length=255, verbose_name='plaats'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='castle',
            name='provincie',
            field=models.CharField(default='111', max_length=25, verbose_name='provincie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='castle',
            name='rijksmonnr',
            field=models.IntegerField(default=122, verbose_name='Rijksmonnr'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='castle',
            name='typering',
            field=models.CharField(default='ssss', max_length=255, verbose_name='typering'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='castle',
            name='zichtbaar',
            field=models.BooleanField(default=False, verbose_name='zichtbaar'),
        ),
    ]
